version: 0.0
os: windows
files:
  - source: \
    destination: c:\HardyWebsite
hooks:
  ApplicationStop:
    - location: .\RemoveApp.ps1
      timeout: 30
  ApplicationStart:
    - location: C:\HardyWebsite\InstallApp.ps1
      timeout: 300